module.exports = {
  ADMIN_TOKEN_STATUSES: { REVOKED: 'REVOKED', ACTIVE: 'ACTIVE' },
  ROLES: { USER: 'USER', ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN' },
  ERROR_CODES: {
    SESSION_EXPIRED: 'E001',
    REFRESH_TOKEN_EXPIRED: 'E002',
    MISSING_TOKEN: 'E003',
    MISSING_REFRESH_TOKEN: 'E004',
    INVALID_REFRESH_TOKEN: 'E005',
    DUPLICATE_USER: 'E006',
    SUPER_ADMIN_REG_FAILED: 'E007',
    INVALID_VOTE_TOKEN: 'E008',
    EXPIRED_VOTE_TOKEN: 'E009',
    DUPLICATE_VOTE: 'E010',
  },
  SUB_DOC_OPTIONS: { minimize: false, _id: false, id: false },
};
